// <auto-generated />
namespace p.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_grn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_grn));
        
        string IMigrationMetadata.Id
        {
            get { return "201305220321574_mig_grn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
