// <auto-generated />
namespace p.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mig_store : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_store));
        
        string IMigrationMetadata.Id
        {
            get { return "201305211222307_mig_store"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
